# Generated by Django 4.0.3 on 2022-04-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Door', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Image_recognize',
        ),
        migrations.RenameField(
            model_name='image_recognize',
            old_name='hotel_Main_Img',
            new_name='Image_recognize_main',
        ),
    ]
